### PR TITLE
[Bugfix] Add proper error message when user does not have access to a page + contributors

### PR DESCRIPTION
**Pull request by Frenje123**
If the user does not have privilege to access a page they are asked to log in again, even though they are already logged in.

**To reproduce:**

1. Log in with a lim_web user on one window
2. Open a private window and log in with another user on that window. This user must have a role with added privileges, i.e. admissions
3. Go to an admission page on the private window
4. With the lim_web user, remove the role with the privileges of the other user.
5. Refresh the private window.You are asked to log in again

### CODE REVIEW

**Review by KevinKristiansen — COMMENTED** [review]
Seems good. I was just wondering if the error message should include something along the lines of "If you think you should have access, contact your gjengsjef or MG-web". If it seems unncecessary to add(most people would probably contact us anyways), I can just approve the PR.

**Comment by Frenje123** [comment]
> Seems good. I was just wondering if the error message should include something along the lines of "If you think you should have access, contact your gjengsjef or MG-web". If it seems unncecessary to add(most people would probably contact us anyways), I can just approve the PR.

Should be the group leader, so they can verify their access. But yes I agree.

**Comment by Frenje123** [comment]
> Seems good. I was just wondering if the error message should include something along the lines of "If you think you should have access, contact your gjengsjef or MG-web". If it seems unncecessary to add(most people would probably contact us anyways), I can just approve the PR.

I changed it so it shows an error message to those with roles (making the assumption that they are all internals of Samfundet)

**Review by robines — APPROVED** [review]
LGTM

**Pull request merged**
