### PR TITLE
[Change] Remove redirect to new applicant upon login failure

### PR DESCRIPTION
**Pull request by Frenje123**
- Redirects applicant to registration page if their user does not exist
- Right now we always redirect users if they fill in incorrect info. This can cause a lot of confusion
- If they do exist, they will know that their password was incorrect

### CODE REVIEW

**Review by KevinKristiansen — COMMENTED** [review]
The behaviour of directly redirecting someone to the registration page if their email isn't registered seems like a potential cause for confusion for users who make a typio in their email. Since they are automatically redirected, they won't get to look over their email to see if it is correctly written, which might lead them to believe their account has been deleted, which in turn leads to extra hassle with us getting emailed, or people creating duplicate accounts.

I'm also worried the lockout policy might deter some applicants from applying if they forget/misstype their password 5 times, and have to wait an hour(and maybe forget about the admission) to retry. Is this strictness necessary?

**Comment by Frenje123** [comment]
> The behaviour of directly redirecting someone to the registration page if their email isn't registered seems like a potential cause for confusion for users who make a typio in their email. Since they are automatically redirected, they won't get to look over their email to see if it is correctly written, which might lead them to believe their account has been deleted, which in turn leads to extra hassle with us getting emailed, or people creating duplicate accounts.
> 
> I'm also worried the lockout policy might deter some applicants from applying if they forget/misstype their password 5 times, and have to wait an hour(and maybe forget about the admission) to retry. Is this strictness necessary?

Very good points! Perhaps I should remove the redirect to creating new applicants all together? We have had that spesific redirect for years, but I have never thought about the fact that users could create duplicate accounts due to it.

I also agree with the logout part. The main idea was to use this alongside email verificaiton, to hinder people form sending too many verification emails at once (which is definitely not secure). I might just add a check for hindering that instead of locking out the user all together.

**Comment by Frenje123** [comment]
> The behaviour of directly redirecting someone to the registration page if their email isn't registered seems like a potential cause for confusion for users who make a typio in their email. Since they are automatically redirected, they won't get to look over their email to see if it is correctly written, which might lead them to believe their account has been deleted, which in turn leads to extra hassle with us getting emailed, or people creating duplicate accounts.
> 
> I'm also worried the lockout policy might deter some applicants from applying if they forget/misstype their password 5 times, and have to wait an hour(and maybe forget about the admission) to retry. Is this strictness necessary?

I have removed the lockout mechanism all together and just made the login flow better for applicants. I think it provides better feedback than what we currently do, and along with email validation, I think the chance of creating duplicate accounts goes down to 0.

**Comment by robines** [comment]
I also agree that redirecing to the registration page if the email isn't registered can lead to confusion, so I think it's best to just always redirect to the applicant login page no matter if the email is registered or not.

**Review by robines — APPROVED** [review]

**Comment by KevinKristiansen** [comment]
Looks good, but would it be possible to keep the email field when a login doesn't go through? It's tedious for people to have to retype their email and password even though they just got their password wrong.

**Comment by Frenje123** [comment]
> Looks good, but would it be possible to keep the email field when a login doesn't go through? It's tedious for people to have to retype their email and password even though they just got their password wrong.

I can probably add this in a separate PR later.
Seems like a good solution!

**Pull request merged**
