### PR TITLE
Fix Lyche calendar usability issues

### LINKED ISSUE #581: Usability improvements for Lyche calendar
- Show table size in parenthesis for each row
- Show name on reservations instead of time
- Add padding between neighbour reservations
- Sort reservation list by date

### PR DESCRIPTION
**Pull request by evgiz**
fixes #581 

- Fixes usability issues
- Cleans up css a bit
- Adds missing semicolon on global css includes
- Changes to make locale strings more clear

### CODE REVIEW

**Comment by eirikvaa** [comment]
Fix the Rubocop warnings and I'll deploy it right away :-)

**Comment by evgiz** [comment]
Rubocop is happy now!

**Comment by eirikvaa** [comment]
And all is good in the world

**Review by eirikvaa — APPROVED** [review]

**Comment by evgiz** [comment]
Broken commit history, created new pull request

**Pull request closed without merging**
