### PR TITLE
Update sponsors (add trondheim kommune)

### PR DESCRIPTION
**Pull request by evgiz**
- Change musikkutstyrsordningen to kulturrom with new logo
- Add Trondheim kommune sponsor

(Our previous sponsor MUO has changed their name and branding)

### CODE REVIEW

**Comment by eirikvaa** [comment]
This is how it looks on a small screen:
image

samfundet.no doesn't have this problem, so would be nice to fix that :-)

image

**Comment by evgiz** [comment]
Nice catch! Will fix

**Comment by evgiz** [comment]
Done! Layout on mobile now looks like this:

Screenshot 2020-08-05 at 17 55 10

**Comment by eirikvaa** [comment]
Looks hella good!

**Review by eirikvaa — APPROVED** [review]
Looks delicious to me.

**Pull request merged**
